// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: message/ownmfa_notifier_in.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotifierIn represents notification metadata as used in message queues.
type NotifierIn struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OrgId       *string                `protobuf:"bytes,1,opt,name=org_id,json=orgId"`
	xxx_hidden_AppId       *string                `protobuf:"bytes,2,opt,name=app_id,json=appId"`
	xxx_hidden_IdentityId  *string                `protobuf:"bytes,3,opt,name=identity_id,json=identityId"`
	xxx_hidden_TraceId     []byte                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NotifierIn) Reset() {
	*x = NotifierIn{}
	mi := &file_message_ownmfa_notifier_in_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifierIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifierIn) ProtoMessage() {}

func (x *NotifierIn) ProtoReflect() protoreflect.Message {
	mi := &file_message_ownmfa_notifier_in_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NotifierIn) GetOrgId() string {
	if x != nil {
		if x.xxx_hidden_OrgId != nil {
			return *x.xxx_hidden_OrgId
		}
		return ""
	}
	return ""
}

func (x *NotifierIn) GetAppId() string {
	if x != nil {
		if x.xxx_hidden_AppId != nil {
			return *x.xxx_hidden_AppId
		}
		return ""
	}
	return ""
}

func (x *NotifierIn) GetIdentityId() string {
	if x != nil {
		if x.xxx_hidden_IdentityId != nil {
			return *x.xxx_hidden_IdentityId
		}
		return ""
	}
	return ""
}

func (x *NotifierIn) GetTraceId() []byte {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return nil
}

func (x *NotifierIn) SetOrgId(v string) {
	x.xxx_hidden_OrgId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *NotifierIn) SetAppId(v string) {
	x.xxx_hidden_AppId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *NotifierIn) SetIdentityId(v string) {
	x.xxx_hidden_IdentityId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *NotifierIn) SetTraceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TraceId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *NotifierIn) HasOrgId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NotifierIn) HasAppId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *NotifierIn) HasIdentityId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *NotifierIn) HasTraceId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *NotifierIn) ClearOrgId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OrgId = nil
}

func (x *NotifierIn) ClearAppId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AppId = nil
}

func (x *NotifierIn) ClearIdentityId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IdentityId = nil
}

func (x *NotifierIn) ClearTraceId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TraceId = nil
}

type NotifierIn_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Organization ID (UUID).
	OrgId *string
	// Application ID (UUID).
	AppId *string
	// Identity ID (UUID).
	IdentityId *string
	// Trace ID (UUID).
	TraceId []byte
}

func (b0 NotifierIn_builder) Build() *NotifierIn {
	m0 := &NotifierIn{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OrgId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_OrgId = b.OrgId
	}
	if b.AppId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_AppId = b.AppId
	}
	if b.IdentityId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_IdentityId = b.IdentityId
	}
	if b.TraceId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_TraceId = b.TraceId
	}
	return m0
}

var File_message_ownmfa_notifier_in_proto protoreflect.FileDescriptor

const file_message_ownmfa_notifier_in_proto_rawDesc = "" +
	"\n" +
	" message/ownmfa_notifier_in.proto\x12\x12ownmfa.int.message\"v\n" +
	"\n" +
	"NotifierIn\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1f\n" +
	"\videntity_id\x18\x03 \x01(\tR\n" +
	"identityId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\fR\atraceIdB+Z)github.com/ownmfa/hermes/proto/go/messageb\beditionsp\xe9\a"

var file_message_ownmfa_notifier_in_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_ownmfa_notifier_in_proto_goTypes = []any{
	(*NotifierIn)(nil), // 0: ownmfa.int.message.NotifierIn
}
var file_message_ownmfa_notifier_in_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_ownmfa_notifier_in_proto_init() }
func file_message_ownmfa_notifier_in_proto_init() {
	if File_message_ownmfa_notifier_in_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_ownmfa_notifier_in_proto_rawDesc), len(file_message_ownmfa_notifier_in_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_ownmfa_notifier_in_proto_goTypes,
		DependencyIndexes: file_message_ownmfa_notifier_in_proto_depIdxs,
		MessageInfos:      file_message_ownmfa_notifier_in_proto_msgTypes,
	}.Build()
	File_message_ownmfa_notifier_in_proto = out.File
	file_message_ownmfa_notifier_in_proto_goTypes = nil
	file_message_ownmfa_notifier_in_proto_depIdxs = nil
}
