DROP TYPE IF EXISTS plan;
CREATE TYPE plan AS ENUM ('PLAN_UNSPECIFIED', 'PAYMENT_FAIL', 'STARTER', 'PRO', 'ENTERPRISE');

ALTER TABLE orgs ADD COLUMN status status NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE orgs ALTER COLUMN status DROP DEFAULT;

ALTER TABLE orgs ADD COLUMN plan plan NOT NULL DEFAULT 'STARTER';
ALTER TABLE orgs ALTER COLUMN plan DROP DEFAULT;
