DROP EXTENSION IF EXISTS pgcrypto;
ALTER TABLE orgs ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE users ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE keys ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE apps ALTER COLUMN id SET DEFAULT uuidv7();
ALTER TABLE identities ALTER COLUMN id SET DEFAULT uuidv7();
