// Code generated by MockGen. DO NOT EDIT.
// Source: app_identity.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	api "github.com/ownmfa/api/go/api"
	oath "github.com/ownmfa/hermes/pkg/oath"
)

// MockApper is a mock of Apper interface.
type MockApper struct {
	ctrl     *gomock.Controller
	recorder *MockApperMockRecorder
}

// MockApperMockRecorder is the mock recorder for MockApper.
type MockApperMockRecorder struct {
	mock *MockApper
}

// NewMockApper creates a new mock instance.
func NewMockApper(ctrl *gomock.Controller) *MockApper {
	mock := &MockApper{ctrl: ctrl}
	mock.recorder = &MockApperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApper) EXPECT() *MockApperMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApper) Create(ctx context.Context, app *api.App) (*api.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(*api.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockApperMockRecorder) Create(ctx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApper)(nil).Create), ctx, app)
}

// Delete mocks base method.
func (m *MockApper) Delete(ctx context.Context, appID, orgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, appID, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApperMockRecorder) Delete(ctx, appID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApper)(nil).Delete), ctx, appID, orgID)
}

// List mocks base method.
func (m *MockApper) List(ctx context.Context, orgID string, lBoundTS time.Time, prevID string, limit int32) ([]*api.App, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, lBoundTS, prevID, limit)
	ret0, _ := ret[0].([]*api.App)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockApperMockRecorder) List(ctx, orgID, lBoundTS, prevID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockApper)(nil).List), ctx, orgID, lBoundTS, prevID, limit)
}

// Read mocks base method.
func (m *MockApper) Read(ctx context.Context, appID, orgID string) (*api.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, appID, orgID)
	ret0, _ := ret[0].(*api.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockApperMockRecorder) Read(ctx, appID, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockApper)(nil).Read), ctx, appID, orgID)
}

// Update mocks base method.
func (m *MockApper) Update(ctx context.Context, app *api.App) (*api.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, app)
	ret0, _ := ret[0].(*api.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockApperMockRecorder) Update(ctx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApper)(nil).Update), ctx, app)
}

// MockIdentityer is a mock of Identityer interface.
type MockIdentityer struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityerMockRecorder
}

// MockIdentityerMockRecorder is the mock recorder for MockIdentityer.
type MockIdentityerMockRecorder struct {
	mock *MockIdentityer
}

// NewMockIdentityer creates a new mock instance.
func NewMockIdentityer(ctrl *gomock.Controller) *MockIdentityer {
	mock := &MockIdentityer{ctrl: ctrl}
	mock.recorder = &MockIdentityerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityer) EXPECT() *MockIdentityerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIdentityer) Create(ctx context.Context, identity *api.Identity) (*api.Identity, *oath.OTP, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, identity)
	ret0, _ := ret[0].(*api.Identity)
	ret1, _ := ret[1].(*oath.OTP)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Create indicates an expected call of Create.
func (mr *MockIdentityerMockRecorder) Create(ctx, identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIdentityer)(nil).Create), ctx, identity)
}

// Delete mocks base method.
func (m *MockIdentityer) Delete(ctx context.Context, identityID, orgID, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, identityID, orgID, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIdentityerMockRecorder) Delete(ctx, identityID, orgID, appID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIdentityer)(nil).Delete), ctx, identityID, orgID, appID)
}

// List mocks base method.
func (m *MockIdentityer) List(ctx context.Context, orgID string, lBoundTS time.Time, prevID string, limit int32, appID string) ([]*api.Identity, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, orgID, lBoundTS, prevID, limit, appID)
	ret0, _ := ret[0].([]*api.Identity)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIdentityerMockRecorder) List(ctx, orgID, lBoundTS, prevID, limit, appID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIdentityer)(nil).List), ctx, orgID, lBoundTS, prevID, limit, appID)
}

// Read mocks base method.
func (m *MockIdentityer) Read(ctx context.Context, identityID, orgID, appID string) (*api.Identity, *oath.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, identityID, orgID, appID)
	ret0, _ := ret[0].(*api.Identity)
	ret1, _ := ret[1].(*oath.OTP)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Read indicates an expected call of Read.
func (mr *MockIdentityerMockRecorder) Read(ctx, identityID, orgID, appID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockIdentityer)(nil).Read), ctx, identityID, orgID, appID)
}
