name: Hermes CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.18-alpine
      env:
        GOFLAGS: -buildvcs=false
        TEST_REDIS_HOST: redis
        TEST_PG_URI: pgx://postgres:postgres@postgres/hermes_test
        TEST_NSQ_PUB_ADDR: nsqd:4150
        TEST_NSQ_LOOKUP_ADDRS: nsqlookupd:4161
    env:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hermes_test
      nsqlookupd:
        image: ownmfa/nsqlookupd:v1.2.0
        env:
          LOG_LEVEL: warn
      nsqd:
        image: ownmfa/nsqd:v1.2.0
        env:
          LOOKUP_ADDR: nsqlookupd:4160
          LOG_LEVEL: warn
      redis:
        image: redis:6-alpine
    steps:
      - name: Deps
        # Names are duplicated as IDs for important steps for use by Notify
        id: Deps
        # Add packages needed to support builds and tests
        run: |
          apk update && apk upgrade
          apk add --no-cache make git
          go version
          go env
      - name: Clone
        id: Clone
        uses: actions/checkout@v2
      - name: Build_and_Test
        id: Build_and_Test
        run: make test
      - name: Push
        id: Push
        # GitHub Actions does not currently support Docker within a container
        run: |
          apk add --no-cache docker
          docker version
          docker login -u ownmfa -p ${{ secrets.GHCR_PAT }} ghcr.io
          git config --global --add safe.directory /__w/hermes/hermes
          TAG=$(git rev-parse --short=8 HEAD)
          #docker buildx create --use
          #docker buildx build -f build/Dockerfile -t ghcr.io/ownmfa/hermes:${TAG} --platform linux/amd64,linux/arm64 --push .
          docker build -f build/Dockerfile -t ghcr.io/ownmfa/hermes:${TAG} .
          docker push ghcr.io/ownmfa/hermes:${TAG}
          #docker buildx rm
          docker logout ghcr.io
      - name: Notify
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
